version: '3'
services:
  app:
    build: .
    env_file: .env
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    tty: true
    ports:
      - "${NODE_PORT}:8000"

volumes:
    node_modules: {}