version: '3'
services:
  app:
    image: fsninomiya/kinshai-gatsbyjs
    working_dir: /srv
    volumes:
      - .:/srv
      - node_modules:/srv/node_modules
    tty: true
    ports:
      - 8000:8000

volumes:
    node_modules: {}