version: '3'

services:
  app:
    build: ./docker/node/
    container_name: app
    environment:
      - TZ=Asia/Tokyo
    working_dir: /srv
    volumes:
      - .:/srv
      - node_modules:/srv/app/node_modules #Volume Trick
    ports:
      - "8000:8000"
    tty: true

volumes:
  node_modules: