version: '3'
services:
  app:
    build: .
    working_dir: /srv
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - .:/srv
      - node_modules:/srv/node_modules
    tty: true
    ports:
      - 8000:8000

volumes:
    node_modules: {}