version: '3'
services:
  app:
    image: node:10.15.3-jessie
    working_dir: /app
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    tty: true
    ports:
      - 8000:8000

volumes:
    node_modules: {}