Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.synced_folder "../", "/vagrant", type: "virtualbox"

  #VMからsshを利用する場合はコメント解除して使用する
  #config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.name = "kinshai"
  end

  #初回vagrant up時のみvagrant provisionも同時に実行される
  config.vm.provision "shell",
    path: "provision.sh"
end
