version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3-jessie
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
          paths:
            - app/node_modules

      - run: date

      - run:
          working_directory: ~/repo/app
          command: |
            yarn global add gatsby-cli
            yarn install

      - save_cache:
          paths:
            - app/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          working_directory: ~/repo/app
          command: yarn run lint